@startuml register

actor "Actor"
boundary "register.vue"
control "useUser"
control "store/user"
entity "endpoint"

"Actor" ->  "register.vue" : form
activate register.vue
"register.vue" ->  "useUser" : setRegiser()
activate useUser
"useUser" -> "store/user" : register()
activate "store/user"
"store/user" -> "endpoint" : /api/auth/register
activate endpoint
"endpoint" -> "store/user" : data
deactivate endpoint
"store/user" -> "store/user" : saveData
"store/user" -> "Actor" : redirect
deactivate "store/user"
deactivate useUser
deactivate register.vue  

@enduml