export const route = 'food';

export const FETCH_REQUEST_NOT_SELECTED = 'FETCH_REQUEST_NOT_SELECTED';
export const FETCH_SUCCESS_NOT_SELECTED = 'FETCH_SUCCESS_NOT_SELECTED';
export const FETCH_FAILURE_NOT_SELECTED = 'FETCH_FAILURE_NOT_SELECTED';

export const FETCH_REQUEST_SELECTED = 'FETCH_REQUEST_SELECTED';
export const FETCH_SUCCESS_SELECTED = 'FETCH_SUCCESS_SELECTED';
export const FETCH_FAILURE_SELECTED = 'FETCH_FAILURE_SELECTED';

export const SET_ASSIGN_FETCH_REQUEST = 'SET_ASSIGN_FETCH_REQUEST';
export const SET_ASSIGN_FETCH_SUCCESS = 'SET_ASSIGN_FETCH_SUCCESS';
export const SET_ASSIGN_FETCH_FAILED  = 'SET_ASSIGN_FETCH_FAILED' ;

export const SET_DELETE_FETCH_REQUEST = 'SET_DELETE_FETCH_REQUEST';
export const SET_DELETE_FETCH_SUCCESS = 'SET_DELETE_FETCH_SUCCESS';
export const SET_DELETE_FETCH_FAILED  = 'SET_DELETE_FETCH_FAILED' ;