export const route = 'food';

export const FETCH_REQUEST_NOT_SELECTED = 'FETCH_REQUEST_NOT_SELECTED';
export const FETCH_SUCCESS_NOT_SELECTED = 'FETCH_SUCCESS_NOT_SELECTED';
export const FETCH_FAILURE_NOT_SELECTED = 'FETCH_FAILURE_NOT_SELECTED';

export const FETCH_REQUEST_SELECTED = 'FETCH_REQUEST_SELECTED';
export const FETCH_SUCCESS_SELECTED = 'FETCH_SUCCESS_SELECTED';
export const FETCH_FAILURE_SELECTED = 'FETCH_FAILURE_SELECTED';